sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bEYpRCuc3G7+1v/tpJqaNpcbWYekux5/qvRvF//5+7mEIQZ8DZou1IlKFKK3cLL7ZNY0hEVx7fpVUS+5cqY9Ahqd1tsVqtDExK/Wu+Iuc6IRYc+f5/4p2wmBw3LUAmLjoe8QcjxuNkaMXdJtzFd+d8IxGlTWT+aRbbrn9RcIkojX9wBv7OOdoBrehG657yl3OKbwNbttdP344fWlm7w6kioqcGKDQKITadk7b4bmdZSKOIBi4/goNCF2CdzPgb+H6qP/NVKaLZZM28oqMGN8XFpVDj/PQxSzNA9Vbd+j+BAbPXnbsLSZfuPjDspMNe5ds3wZrv1hDEt/KsyAIv2fX5HwywyNCZnoif3KjxPNlbm3NzG/fHusXVqx8x/fWXBv03bAdhFj4Ek0TS9tm/32T98g0V2Uh8S1G21jjfQYqr9FeuivxgxS+QWFOAsZi6u/1xt78FDH7UYPoUlIdzfh7b/ryzh0kC1iU4zYlu+JWl6Cx9Zy4aXPIaE1R+D1+mHL3JNnvXOJ04r2n0ZS1WeVihTklmWpP8TkTfeaKB0rIs7y7tyg/daIW5EWZ8CNJibD+811ucK8dj3LB0Shj336+VVkpz90xEoQ5aM6uKuBTrLP2/l9Ixas3KD98goNrZdzb/EoPA0BLwV8pP6mSTxZ7H1/K+ln/C2CAvrEsOLjpv8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Heart-Cry-of-Jesus_4323
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy